name: Cron Sync Request

on:
  schedule:
    - cron: "*/5 * * * *"   # co 5 minut
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request cron
        run: |
          curl -X POST "https://develogic.dfirma.pl/wp-json/develogic/v1/sync?secret_key=1234"
